package main

const (
	CAT_RUN_ANIMATION_FRAME_COUNT      = 6
	CAT_RUN_ANIMATION_FRAME_WIDTH      = 48
	CAT_RUN_ANIMATION_FRAME_PER_SECOND = 6
	CAT_DIE_ANIMATION_FRAME_COUNT      = 4

	CAT_FLY_ANIMATION_FRAME_COUNT      = 3
	CAT_FLY_ANIMATION_FRAME_WIDTH      = 19
	CAT_FLY_ANIMATION_FRAME_PER_SECOND = 4
)
